# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentanycast/v1/common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'agentanycast/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61gentanycast/v1/common.proto\x12\x0f\x61gentanycast.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n\x08PeerInfo\x12\x17\n\x07peer_id\x18\x01 \x01(\tR\x06peerId\x12\x1c\n\taddresses\x18\x02 \x03(\tR\taddresses\x12H\n\x0f\x63onnection_type\x18\x03 \x01(\x0e\x32\x1f.agentanycast.v1.ConnectionTypeR\x0e\x63onnectionType\x12=\n\x0c\x63onnected_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0b\x63onnectedAt\"\x81\x02\n\x08NodeInfo\x12\x17\n\x07peer_id\x18\x01 \x01(\tR\x06peerId\x12)\n\x10listen_addresses\x18\x02 \x03(\tR\x0flistenAddresses\x12\x33\n\x08nat_type\x18\x03 \x01(\x0e\x32\x18.agentanycast.v1.NATTypeR\x07natType\x12\'\n\x0f\x63onnected_peers\x18\x04 \x01(\x05R\x0e\x63onnectedPeers\x12\x39\n\nstarted_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\x12\x18\n\x07version\x18\x06 \x01(\tR\x07version\"\xc0\x01\n\x0b\x45rrorDetail\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12\x46\n\x08metadata\x18\x03 \x03(\x0b\x32*.agentanycast.v1.ErrorDetail.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01*h\n\x0e\x43onnectionType\x12\x1f\n\x1b\x43ONNECTION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x43ONNECTION_TYPE_DIRECT\x10\x01\x12\x19\n\x15\x43ONNECTION_TYPE_RELAY\x10\x02*N\n\x07NATType\x12\x18\n\x14NAT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fNAT_TYPE_PUBLIC\x10\x01\x12\x14\n\x10NAT_TYPE_PRIVATE\x10\x02\x42RZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentanycast.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1'
  _globals['_ERRORDETAIL_METADATAENTRY']._loaded_options = None
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CONNECTIONTYPE']._serialized_start=742
  _globals['_CONNECTIONTYPE']._serialized_end=846
  _globals['_NATTYPE']._serialized_start=848
  _globals['_NATTYPE']._serialized_end=926
  _globals['_PEERINFO']._serialized_start=83
  _globals['_PEERINFO']._serialized_end=285
  _globals['_NODEINFO']._serialized_start=288
  _globals['_NODEINFO']._serialized_end=545
  _globals['_ERRORDETAIL']._serialized_start=548
  _globals['_ERRORDETAIL']._serialized_end=740
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_start=681
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_end=740
# @@protoc_insertion_point(module_scope)
