# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentanycast/v1/federation.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'agentanycast/v1/federation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from agentanycast.v1 import registry_service_pb2 as agentanycast_dot_v1_dot_registry__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n agentanycast/v1/federation.proto\x12\x0f\x61gentanycast.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&agentanycast/v1/registry_service.proto\"}\n\x18SyncRegistrationsRequest\x12\x19\n\x08relay_id\x18\x01 \x01(\tR\x07relayId\x12\x30\n\x05since\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x05since\x12\x14\n\x05limit\x18\x03 \x01(\x05R\x05limit\"\xac\x01\n\x19SyncRegistrationsResponse\x12L\n\rregistrations\x18\x01 \x03(\x0b\x32&.agentanycast.v1.FederatedRegistrationR\rregistrations\x12\x41\n\x0esync_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\rsyncTimestamp\"\x83\x01\n\x18PushRegistrationsRequest\x12\x19\n\x08relay_id\x18\x01 \x01(\tR\x07relayId\x12L\n\rregistrations\x18\x02 \x03(\x0b\x32&.agentanycast.v1.FederatedRegistrationR\rregistrations\"S\n\x19PushRegistrationsResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x05R\x08\x61\x63\x63\x65pted\x12\x1a\n\x08rejected\x18\x02 \x01(\x05R\x08rejected\"\xee\x02\n\x15\x46\x65\x64\x65ratedRegistration\x12\x17\n\x07peer_id\x18\x01 \x01(\tR\x06peerId\x12&\n\x0forigin_relay_id\x18\x02 \x01(\tR\roriginRelayId\x12\x32\n\x06skills\x18\x03 \x03(\x0b\x32\x1a.agentanycast.v1.SkillInfoR\x06skills\x12\x1d\n\nagent_name\x18\x04 \x01(\tR\tagentName\x12+\n\x11\x61gent_description\x18\x05 \x01(\tR\x10\x61gentDescription\x12?\n\rregistered_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0cregisteredAt\x12\x39\n\nexpires_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n\x07version\x18\x08 \x01(\x04R\x07version2\xeb\x01\n\x11\x46\x65\x64\x65rationService\x12j\n\x11SyncRegistrations\x12).agentanycast.v1.SyncRegistrationsRequest\x1a*.agentanycast.v1.SyncRegistrationsResponse\x12j\n\x11PushRegistrations\x12).agentanycast.v1.PushRegistrationsRequest\x1a*.agentanycast.v1.PushRegistrationsResponseBRZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentanycast.v1.federation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1'
  _globals['_SYNCREGISTRATIONSREQUEST']._serialized_start=126
  _globals['_SYNCREGISTRATIONSREQUEST']._serialized_end=251
  _globals['_SYNCREGISTRATIONSRESPONSE']._serialized_start=254
  _globals['_SYNCREGISTRATIONSRESPONSE']._serialized_end=426
  _globals['_PUSHREGISTRATIONSREQUEST']._serialized_start=429
  _globals['_PUSHREGISTRATIONSREQUEST']._serialized_end=560
  _globals['_PUSHREGISTRATIONSRESPONSE']._serialized_start=562
  _globals['_PUSHREGISTRATIONSRESPONSE']._serialized_end=645
  _globals['_FEDERATEDREGISTRATION']._serialized_start=648
  _globals['_FEDERATEDREGISTRATION']._serialized_end=1014
  _globals['_FEDERATIONSERVICE']._serialized_start=1017
  _globals['_FEDERATIONSERVICE']._serialized_end=1252
# @@protoc_insertion_point(module_scope)
