# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agentanycast.v1 import federation_pb2 as agentanycast_dot_v1_dot_federation__pb2


class FederationServiceStub(object):
    """FederationService enables relay-to-relay skill registry synchronization.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncRegistrations = channel.unary_unary(
                '/agentanycast.v1.FederationService/SyncRegistrations',
                request_serializer=agentanycast_dot_v1_dot_federation__pb2.SyncRegistrationsRequest.SerializeToString,
                response_deserializer=agentanycast_dot_v1_dot_federation__pb2.SyncRegistrationsResponse.FromString,
                _registered_method=True)
        self.PushRegistrations = channel.unary_unary(
                '/agentanycast.v1.FederationService/PushRegistrations',
                request_serializer=agentanycast_dot_v1_dot_federation__pb2.PushRegistrationsRequest.SerializeToString,
                response_deserializer=agentanycast_dot_v1_dot_federation__pb2.PushRegistrationsResponse.FromString,
                _registered_method=True)


class FederationServiceServicer(object):
    """FederationService enables relay-to-relay skill registry synchronization.
    """

    def SyncRegistrations(self, request, context):
        """SyncRegistrations pulls registration updates from a peer relay.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushRegistrations(self, request, context):
        """PushRegistrations sends local registration changes to a peer relay.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncRegistrations': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncRegistrations,
                    request_deserializer=agentanycast_dot_v1_dot_federation__pb2.SyncRegistrationsRequest.FromString,
                    response_serializer=agentanycast_dot_v1_dot_federation__pb2.SyncRegistrationsResponse.SerializeToString,
            ),
            'PushRegistrations': grpc.unary_unary_rpc_method_handler(
                    servicer.PushRegistrations,
                    request_deserializer=agentanycast_dot_v1_dot_federation__pb2.PushRegistrationsRequest.FromString,
                    response_serializer=agentanycast_dot_v1_dot_federation__pb2.PushRegistrationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentanycast.v1.FederationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentanycast.v1.FederationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederationService(object):
    """FederationService enables relay-to-relay skill registry synchronization.
    """

    @staticmethod
    def SyncRegistrations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentanycast.v1.FederationService/SyncRegistrations',
            agentanycast_dot_v1_dot_federation__pb2.SyncRegistrationsRequest.SerializeToString,
            agentanycast_dot_v1_dot_federation__pb2.SyncRegistrationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushRegistrations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentanycast.v1.FederationService/PushRegistrations',
            agentanycast_dot_v1_dot_federation__pb2.PushRegistrationsRequest.SerializeToString,
            agentanycast_dot_v1_dot_federation__pb2.PushRegistrationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
