# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentanycast/v1/streaming.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'agentanycast/v1/streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61gentanycast/v1/streaming.proto\x12\x0f\x61gentanycast.v1\"\xb3\x02\n\x0bStreamStart\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n\x0b\x61rtifact_id\x18\x02 \x01(\tR\nartifactId\x12#\n\rartifact_name\x18\x03 \x01(\tR\x0c\x61rtifactName\x12\x1d\n\nmedia_type\x18\x04 \x01(\tR\tmediaType\x12!\n\x0ctotal_chunks\x18\x05 \x01(\x05R\x0btotalChunks\x12\x46\n\x08metadata\x18\x06 \x03(\x0b\x32*.agentanycast.v1.StreamStart.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\x90\x01\n\x0bStreamChunk\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n\x0b\x61rtifact_id\x18\x02 \x01(\tR\nartifactId\x12\x1a\n\x08sequence\x18\x03 \x01(\x05R\x08sequence\x12\x12\n\x04\x64\x61ta\x18\x04 \x01(\x0cR\x04\x64\x61ta\x12\x17\n\x07is_last\x18\x05 \x01(\x08R\x06isLast\"\x7f\n\tStreamEnd\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n\x0b\x61rtifact_id\x18\x02 \x01(\tR\nartifactId\x12\x38\n\x06reason\x18\x03 \x01(\x0e\x32 .agentanycast.v1.StreamEndReasonR\x06reason*\x91\x01\n\x0fStreamEndReason\x12!\n\x1dSTREAM_END_REASON_UNSPECIFIED\x10\x00\x12\x1e\n\x1aSTREAM_END_REASON_COMPLETE\x10\x01\x12\x1e\n\x1aSTREAM_END_REASON_CANCELED\x10\x02\x12\x1b\n\x17STREAM_END_REASON_ERROR\x10\x03\x42RZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentanycast.v1.streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1'
  _globals['_STREAMSTART_METADATAENTRY']._loaded_options = None
  _globals['_STREAMSTART_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_STREAMENDREASON']._serialized_start=639
  _globals['_STREAMENDREASON']._serialized_end=784
  _globals['_STREAMSTART']._serialized_start=53
  _globals['_STREAMSTART']._serialized_end=360
  _globals['_STREAMSTART_METADATAENTRY']._serialized_start=301
  _globals['_STREAMSTART_METADATAENTRY']._serialized_end=360
  _globals['_STREAMCHUNK']._serialized_start=363
  _globals['_STREAMCHUNK']._serialized_end=507
  _globals['_STREAMEND']._serialized_start=509
  _globals['_STREAMEND']._serialized_end=636
# @@protoc_insertion_point(module_scope)
