import { randomUUID } from "node:crypto";
import { chmod, lstat, mkdir, open, readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import YAML from "yaml";
import { profileConfigPath, readProfileConfigYaml, resolveHermesProfilesDir, validateHermesProfileName } from "./hermes-profile-config.js";

const MAX_TEXT_BYTES = 512 * 1024;
const SKILL_NAME = /^[a-z0-9][a-z0-9_-]{0,63}$/;
const TEXT_EXTENSIONS = new Set([".md", ".txt", ".json", ".yaml", ".yml", ".ts", ".js", ".py", ".sh"]);
const SECRET_PATTERN = /(?:-----BEGIN (?:[A-Z ]*PRIVATE KEY|OPENSSH PRIVATE KEY)-----|\b(?:api[_-]?key|secret|token|password)\s*[:=]\s*['"]?[A-Za-z0-9_\-/+=]{16,})/i;

export type PoolSkill = { name: string; category: string; description: string; tags: string[]; files: Array<{ path: string; sizeBytes: number; editable: boolean }>; consumerCount: number };
export type EffectiveSkill = { name: string; description: string; origin: "profile" | "shared_pool" | "builtin" | "external"; effective: boolean; enabled: boolean; editable: boolean; assigned: boolean; shadowed: boolean; status: "enabled" | "disabled" | "shadowed"; category: string | null };
export interface SharedSkillPoolOptions { poolRoot?: string; profilesDir?: string; builtinSkillsDir?: string; }
export class SharedSkillPoolError extends Error { constructor(message: string, public readonly code: "invalid" | "not_found" | "conflict" = "invalid", public readonly impact?: { profiles: string[] }) { super(message); } }

const locks = new Map<string, Promise<void>>();
async function serialized<T>(key: string, operation: () => Promise<T>): Promise<T> {
  const prior = locks.get(key) ?? Promise.resolve(); let release!: () => void;
  const mine = new Promise<void>((resolve) => { release = resolve; }); locks.set(key, prior.then(() => mine));
  await prior;
  try { return await operation(); } finally { release(); if (locks.get(key) === mine) locks.delete(key); }
}
function root(options: SharedSkillPoolOptions) { return path.resolve(options.poolRoot ?? process.env.HERMES_SHARED_SKILLS_DIR ?? path.join(os.homedir(), ".hermes", "skills", "shared")); }
function manifestPath(options: SharedSkillPoolOptions) { return path.join(root(options), "pool-manifest.json"); }
function contained(base: string, candidate: string) { const rel = path.relative(base, candidate); return rel !== "" && !rel.startsWith(`..${path.sep}`) && rel !== ".." && !path.isAbsolute(rel); }
function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function strings(value: unknown) { return Array.isArray(value) ? value.filter((value): value is string => typeof value === "string").map((value) => value.trim()).filter(Boolean) : []; }
function safeName(value: unknown) { const name = typeof value === "string" ? value.trim() : ""; if (!SKILL_NAME.test(name)) throw new SharedSkillPoolError("Skill name must be 1–64 lowercase letters, digits, hyphens, or underscores."); return name; }
function safeRelative(value: string) { const normalized = value.replace(/\\/g, "/"); const parts = normalized.split("/"); if (!normalized || path.isAbsolute(normalized) || parts.some((part) => !part || part === "." || part === "..") || !["SKILL.md", "references", "templates", "scripts", "assets"].includes(parts[0]!)) throw new SharedSkillPoolError("Invalid managed skill file path."); if (parts[0] === "SKILL.md" && parts.length !== 1) throw new SharedSkillPoolError("SKILL.md must be the entry file."); return normalized; }
function editable(relative: string) { return relative === "SKILL.md" || (relative.split("/")[0] !== "assets" && TEXT_EXTENSIONS.has(path.extname(relative).toLowerCase())); }
function checkText(value: string) { if (Buffer.byteLength(value, "utf8") > MAX_TEXT_BYTES) throw new SharedSkillPoolError("Skill text exceeds the maximum size."); if (SECRET_PATTERN.test(value)) throw new SharedSkillPoolError("Skill content appears to contain a credential or private key."); }
function frontmatter(content: string, expectedName?: string) { checkText(content); if (!content.startsWith("---\n")) throw new SharedSkillPoolError("SKILL.md must start with YAML frontmatter."); const end = content.indexOf("\n---", 4); if (end < 0) throw new SharedSkillPoolError("SKILL.md frontmatter is not closed."); let parsed: unknown; try { parsed = YAML.parse(content.slice(4, end)); } catch { throw new SharedSkillPoolError("SKILL.md frontmatter is invalid YAML."); } const data = record(parsed); const name = safeName(data.name); if (expectedName && name !== expectedName) throw new SharedSkillPoolError("SKILL.md frontmatter name does not match the pool entry."); return { name, description: typeof data.description === "string" ? data.description.trim().slice(0, 500) : "" }; }
async function regular(file: string, directory = false) { let entry; try { entry = await lstat(file); } catch (error) { throw new SharedSkillPoolError(`Shared pool filesystem entry is unavailable: ${(error as NodeJS.ErrnoException).code ?? "error"}`); } if (entry.isSymbolicLink() || (directory ? !entry.isDirectory() : !entry.isFile())) throw new SharedSkillPoolError(directory ? "Skill directories must be real directories and must not be symbolic links." : "Skill files must be regular files and must not be symbolic links."); }
async function ensureRoot(options: SharedSkillPoolOptions) { const pool = root(options); try { await mkdir(pool, { recursive: true }); await regular(pool, true); } catch (error) { if (error instanceof SharedSkillPoolError) throw error; throw new SharedSkillPoolError("Unable to access the shared skill pool."); } return pool; }
async function atomic(file: string, content: string, mode?: number) { const dir = path.dirname(file); await regular(dir, true); const actualMode = mode ?? 0o600; const tmp = path.join(dir, `.${path.basename(file)}.${randomUUID()}.tmp`); const handle = await open(tmp, "wx", actualMode); try { await handle.writeFile(content, "utf8"); await handle.sync(); } finally { await handle.close(); } await rename(tmp, file); }
async function existingMode(file: string, fallback = 0o600) { try { return (await stat(file)).mode & 0o777; } catch { return fallback; } }
function refreshMetadata(manifest: Record<string, unknown>) { const categories = record(manifest.categories); let totalSkills = 0; for (const category of Object.values(categories)) totalSkills += Object.keys(record(record(category).skills)).length; const metadata = record(manifest.metadata); manifest.metadata = { ...metadata, total_skills: totalSkills, total_categories: Object.keys(categories).filter((category) => Object.keys(record(record(categories[category]).skills)).length > 0).length, last_updated: new Date().toISOString() }; }
async function readManifest(options: SharedSkillPoolOptions) { await ensureRoot(options); const file = manifestPath(options); let raw: string; try { await regular(file); raw = await readFile(file, "utf8"); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { version: "1.0", categories: {} as Record<string, unknown> }; if (error instanceof SharedSkillPoolError && (error as Error).message.includes("unavailable: ENOENT")) return { version: "1.0", categories: {} as Record<string, unknown> }; if (error instanceof SharedSkillPoolError) throw error; throw new SharedSkillPoolError("Unable to read shared pool manifest."); } let value: unknown; try { value = JSON.parse(raw); } catch { throw new SharedSkillPoolError("Shared pool manifest is corrupt."); } const data = record(value); if (!data.categories || typeof data.categories !== "object" || Array.isArray(data.categories)) throw new SharedSkillPoolError("Shared pool manifest is corrupt."); return data; }
async function writeManifest(options: SharedSkillPoolOptions, manifest: Record<string, unknown>) { refreshMetadata(manifest); await atomic(manifestPath(options), `${JSON.stringify(manifest, null, 2)}\n`, await existingMode(manifestPath(options))); }
function entries(manifest: Record<string, unknown>, poolRoot: string) { const out: Array<{ name: string; category: string; meta: Record<string, unknown>; relative: string }> = []; for (const [category, rawCategory] of Object.entries(record(manifest.categories))) { safeName(category); const skills = record(record(rawCategory).skills); for (const [key, raw] of Object.entries(skills)) { const name = safeName(key); const meta = record(raw); const relative = typeof meta.path === "string" ? meta.path : ""; if (relative !== `${category}/${name}` || !contained(poolRoot, path.resolve(poolRoot, relative))) throw new SharedSkillPoolError("Shared pool manifest contains an invalid skill path."); out.push({ name, category, meta, relative }); } } return out; }
async function filesFor(dir: string, relative = ""): Promise<Array<{ path: string; sizeBytes: number; editable: boolean }>> { await regular(dir, true); const result: Array<{ path: string; sizeBytes: number; editable: boolean }> = []; for (const item of await readdir(dir, { withFileTypes: true })) { if (item.name.startsWith(".")) continue; const next = relative ? `${relative}/${item.name}` : item.name; const file = path.join(dir, item.name); safeRelative(next); if (item.isSymbolicLink()) throw new SharedSkillPoolError("Skill directories must not contain symbolic links."); if (item.isDirectory()) result.push(...await filesFor(file, next)); else { await regular(file); result.push({ path: next, sizeBytes: (await stat(file)).size, editable: editable(next) }); } } return result.sort((a, b) => a.path.localeCompare(b.path)); }
async function profileNames(options: SharedSkillPoolOptions) { try { return (await readdir(options.profilesDir ?? resolveHermesProfilesDir(), { withFileTypes: true })).filter((entry) => entry.isDirectory() && !entry.isSymbolicLink()).map((entry) => entry.name); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw new SharedSkillPoolError("Unable to enumerate Hermes profiles."); } }
function externalDirs(config: Record<string, unknown>, profilesDir: string) { return strings(record(config.skills).external_dirs).map((entry) => path.resolve(entry.startsWith("~") ? path.join(os.homedir(), entry.slice(1)) : path.isAbsolute(entry) ? entry : path.join(path.dirname(profilesDir), entry))); }

export async function listSharedPool(options: SharedSkillPoolOptions = {}): Promise<PoolSkill[]> { const pool = root(options); const manifest = await readManifest(options); const consumers = await profileNames(options); const output: PoolSkill[] = []; for (const entry of entries(manifest, pool)) { const dir = path.resolve(pool, entry.relative); if (!contained(pool, dir)) throw new SharedSkillPoolError("Shared pool manifest escapes its root."); await regular(path.dirname(dir), true); await regular(dir, true); const markdown = path.join(dir, "SKILL.md"); await regular(markdown); const fm = frontmatter(await readFile(markdown, "utf8"), entry.name); const consumerCount = (await Promise.all(consumers.map(async (profile) => (await effectiveProfileSkills(profile, options)).some((skill) => skill.name === entry.name && skill.origin === "shared_pool" && skill.effective && skill.enabled)))).filter(Boolean).length; output.push({ name: entry.name, category: entry.category, description: fm.description || String(entry.meta.description ?? ""), tags: strings(entry.meta.tags), files: await filesFor(dir), consumerCount }); } return output.sort((a, b) => a.name.localeCompare(b.name)); }
export async function getSharedPoolSkill(name: string, options: SharedSkillPoolOptions = {}) { const skill = (await listSharedPool(options)).find((entry) => entry.name === safeName(name)); if (!skill) throw new SharedSkillPoolError("Shared skill was not found.", "not_found"); const content: Record<string, string> = {}; for (const file of skill.files) if (file.editable) content[file.path] = await readFile(path.join(root(options), skill.category, skill.name, file.path), "utf8"); return { ...skill, content }; }
function validateFiles(files: Record<string, string>, name: string) { if (!files?.["SKILL.md"]) throw new SharedSkillPoolError("SKILL.md is required."); frontmatter(files["SKILL.md"], name); for (const [relative, content] of Object.entries(files)) { safeRelative(relative); if (!editable(relative)) throw new SharedSkillPoolError("Only approved text skill files can be edited."); if (typeof content !== "string") throw new SharedSkillPoolError("Skill file content must be text."); checkText(content); } }
export async function createSharedPoolSkill(input: { name: string; category: string; description?: string; tags?: string[]; files: Record<string, string> }, options: SharedSkillPoolOptions = {}) { return serialized(root(options), async () => { const name = safeName(input.name); const category = safeName(input.category); validateFiles(input.files, name); const pool = await ensureRoot(options); const manifest = await readManifest(options); if (entries(manifest, pool).some((entry) => entry.name === name)) throw new SharedSkillPoolError("A shared skill with this name already exists.", "conflict"); const categoryDir = path.join(pool, category); await mkdir(categoryDir, { recursive: true }); await regular(categoryDir, true); const destination = path.join(categoryDir, name); if (!contained(pool, destination)) throw new SharedSkillPoolError("Invalid skill path."); try { await mkdir(destination, { recursive: false }); await regular(destination, true); for (const [relative, content] of Object.entries(input.files)) { const file = path.join(destination, relative); await mkdir(path.dirname(file), { recursive: true }); await regular(path.dirname(file), true); await atomic(file, content); } const categories = record(manifest.categories); const oldCategory = record(categories[category]); const skills = record(oldCategory.skills); skills[name] = { name, ...record(skills[name]), description: input.description?.trim() || frontmatter(input.files["SKILL.md"], name).description, tags: input.tags ?? strings(skills[name] && record(skills[name]).tags), path: `${category}/${name}` }; categories[category] = { ...oldCategory, skills }; manifest.categories = categories; await writeManifest(options, manifest); } catch (error) { await rm(destination, { recursive: true, force: true }); if (error instanceof SharedSkillPoolError) throw error; throw new SharedSkillPoolError("Unable to create shared skill."); } return getSharedPoolSkill(name, options); }); }
export async function updateSharedPoolSkill(name: string, input: { files: Record<string, string>; category?: string; description?: string; tags?: string[] }, options: SharedSkillPoolOptions = {}) { return serialized(root(options), async () => { const existing = await getSharedPoolSkill(name, options); const nextCategory = input.category ? safeName(input.category) : existing.category; validateFiles(input.files, existing.name); const source = path.join(root(options), existing.category, existing.name); const target = path.join(root(options), nextCategory, existing.name); await regular(path.dirname(source), true); await regular(source, true); await mkdir(path.dirname(target), { recursive: true }); await regular(path.dirname(target), true); if (source !== target) { try { await regular(target, true); throw new SharedSkillPoolError("A shared skill already exists at the requested category.", "conflict"); } catch (error) { if (!(error instanceof SharedSkillPoolError) || !error.message.includes("ENOENT")) throw error; } } const stage = `${target}.${randomUUID()}.stage`; const old = `${source}.${randomUUID()}.old`; try { await mkdir(stage); for (const [relative, content] of Object.entries(input.files)) { const file = path.join(stage, relative); await mkdir(path.dirname(file), { recursive: true }); await atomic(file, content); } await chmod(stage, (await stat(source)).mode & 0o777); await rename(source, old); await rename(stage, target); const manifest = await readManifest(options); const categories = record(manifest.categories); const oldCategory = record(categories[existing.category]); const oldSkills = record(oldCategory.skills); const metadata = { ...record(oldSkills[existing.name]), description: input.description?.trim() || frontmatter(input.files["SKILL.md"], existing.name).description, tags: input.tags ?? strings(record(oldSkills[existing.name]).tags), path: `${nextCategory}/${existing.name}` }; delete oldSkills[existing.name]; categories[existing.category] = { ...oldCategory, skills: oldSkills }; const category = record(categories[nextCategory]); const skills = record(category.skills); skills[existing.name] = metadata; categories[nextCategory] = { ...category, skills }; manifest.categories = categories; await writeManifest(options, manifest); await rm(old, { recursive: true, force: true }); } catch (error) { await rm(stage, { recursive: true, force: true }); try { await lstat(old); await rm(target, { recursive: true, force: true }); await rename(old, source); } catch { /* source was not swapped */ } if (error instanceof SharedSkillPoolError) throw error; throw new SharedSkillPoolError("Unable to update shared skill."); } return getSharedPoolSkill(existing.name, options); }); }
export async function deleteSharedPoolSkill(name: string, confirm = false, options: SharedSkillPoolOptions = {}) { return serialized(root(options), async () => { const skill = await getSharedPoolSkill(name, options); const consumers = (await profileNames(options)).filter(async () => false); const active: string[] = []; for (const profile of await profileNames(options)) if ((await effectiveProfileSkills(profile, options)).some((item) => item.name === skill.name && item.origin === "shared_pool" && item.effective && item.enabled)) active.push(profile); if (active.length && !confirm) throw new SharedSkillPoolError("Shared skill has active profile consumers; confirmation is required.", "conflict", { profiles: active }); const target = path.join(root(options), skill.category, skill.name); const trash = `${target}.${randomUUID()}.deleting`; await rename(target, trash); try { const manifest = await readManifest(options); const category = record(record(manifest.categories)[skill.category]); const skills = record(category.skills); delete skills[skill.name]; record(manifest.categories)[skill.category] = { ...category, skills }; await writeManifest(options, manifest); await rm(trash, { recursive: true, force: true }); } catch (error) { await rename(trash, target); if (error instanceof SharedSkillPoolError) throw error; throw new SharedSkillPoolError("Unable to delete shared skill."); } void consumers; return { deleted: true, affectedProfiles: active }; }); }
async function* walk(dir: string): AsyncGenerator<string> { try { await regular(dir, true); for (const entry of await readdir(dir, { withFileTypes: true })) { const full = path.join(dir, entry.name); if (entry.isSymbolicLink()) continue; if (entry.isDirectory()) yield* walk(full); else if (entry.isFile()) yield full; } } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT" && !(error instanceof SharedSkillPoolError && error.message.includes("ENOENT"))) throw error; } }
async function scanSkills(dir: string, origin: EffectiveSkill["origin"], disabled: Set<string>, assigned: Set<string>) { const output: EffectiveSkill[] = []; for await (const file of walk(dir)) { if (path.basename(file) !== "SKILL.md") continue; try { const fm = frontmatter(await readFile(file, "utf8")); const enabled = !disabled.has(fm.name); output.push({ name: fm.name, description: fm.description, origin, effective: enabled, enabled, editable: origin !== "builtin", assigned: assigned.has(fm.name), shadowed: false, status: enabled ? "enabled" : "disabled", category: path.basename(path.dirname(path.dirname(file))) || null }); } catch (error) { if (error instanceof SharedSkillPoolError) throw error; } } return output; }
export async function effectiveProfileSkills(profileName: string, options: SharedSkillPoolOptions = {}): Promise<EffectiveSkill[]> { const profile = validateHermesProfileName(profileName); const profilesDir = options.profilesDir ?? resolveHermesProfilesDir(); const config = await readProfileConfigYaml(profileConfigPath(profile, profilesDir)) ?? {}; const skillsConfig = record(config.skills); const disabled = new Set(strings(skillsConfig.disabled)); const assigned = new Set(strings(record(config.agency).skills)); const roots: Array<[string, EffectiveSkill["origin"]]> = [[path.join(profilesDir, profile, "skills"), "profile"]]; for (const external of externalDirs(config, profilesDir)) roots.push([external, path.resolve(external) === root(options) ? "shared_pool" : "external"]); roots.push([options.builtinSkillsDir ?? process.env.HERMES_BUILTIN_SKILLS_DIR ?? path.join(os.homedir(), ".hermes", "hermes-agent", "skills"), "builtin"]); const result: EffectiveSkill[] = []; const seen = new Set<string>(); for (const [dir, origin] of roots) for (const item of await scanSkills(dir, origin, disabled, assigned)) { if (seen.has(item.name)) result.push({ ...item, effective: false, shadowed: true, status: "shadowed" }); else { seen.add(item.name); result.push(item); } } return result.sort((a, b) => a.name.localeCompare(b.name) || Number(a.shadowed) - Number(b.shadowed)); }
export async function setProfilePoolSkill(profileName: string, name: string, enabled: boolean, options: SharedSkillPoolOptions = {}) { const profile = validateHermesProfileName(profileName); const skill = await getSharedPoolSkill(name, options); const current = await effectiveProfileSkills(profile, options); const poolEntry = current.find((item) => item.name === skill.name && item.origin === "shared_pool"); if (!poolEntry) throw new SharedSkillPoolError("This shared skill is not configured for the agent profile.", "conflict"); if (!enabled && !poolEntry.effective) throw new SharedSkillPoolError("Cannot detach a shared skill that is shadowed by a higher-precedence local skill; the local skill remains effective.", "conflict"); const profilesDir = options.profilesDir ?? resolveHermesProfilesDir(); const configPath = profileConfigPath(profile, profilesDir); return serialized(configPath, async () => { const config = await readProfileConfigYaml(configPath) ?? {}; const skills = record(config.skills); const disabled = new Set(strings(skills.disabled)); if (enabled) disabled.delete(skill.name); else disabled.add(skill.name); skills.disabled = [...disabled].sort(); config.skills = skills; await mkdir(path.dirname(configPath), { recursive: true }); await atomic(configPath, YAML.stringify(config, { sortMapEntries: false }), await existingMode(configPath)); return effectiveProfileSkills(profile, options); }); }

/** Read/write only a profile's own skills tree. Shared/builtin names deliberately cannot be
 * addressed here: callers must use their canonical source editor instead. */
async function profileLocalDirectory(profileName: string, name: string, options: SharedSkillPoolOptions) {
  const profile = validateHermesProfileName(profileName); const skill = safeName(name);
  const profiles = path.resolve(options.profilesDir ?? resolveHermesProfilesDir());
  const directory = path.resolve(profiles, profile, "skills", skill);
  if (!contained(path.resolve(profiles, profile, "skills"), directory)) throw new SharedSkillPoolError("Invalid local skill path.");
  await regular(directory, true); await regular(path.join(directory, "SKILL.md"));
  const parsed = frontmatter(await readFile(path.join(directory, "SKILL.md"), "utf8"), skill);
  if (parsed.name !== skill) throw new SharedSkillPoolError("Profile-local skill metadata does not match its directory.");
  return directory;
}
export async function getProfileLocalSkill(profileName: string, name: string, options: SharedSkillPoolOptions = {}) {
  let dir: string; try { dir = await profileLocalDirectory(profileName, name, options); } catch (error) {
    if (error instanceof SharedSkillPoolError && error.message.includes("ENOENT")) throw new SharedSkillPoolError("Profile-local skill was not found.", "not_found"); throw error;
  }
  const content: Record<string, string> = {}; const files = await filesFor(dir);
  for (const file of files) if (file.editable) content[file.path] = await readFile(path.join(dir, file.path), "utf8");
  const fm = frontmatter(content["SKILL.md"]!, safeName(name));
  return { name: safeName(name), description: fm.description, files, content };
}
export async function updateProfileLocalSkill(profileName: string, name: string, input: { files: Record<string, string> }, options: SharedSkillPoolOptions = {}) {
  const profile = validateHermesProfileName(profileName); const skill = safeName(name); validateFiles(input.files, skill);
  const lock = profileConfigPath(profile, options.profilesDir ?? resolveHermesProfilesDir());
  return serialized(lock, async () => {
    const target = await profileLocalDirectory(profile, skill, options); const stage = `${target}.${randomUUID()}.stage`; const old = `${target}.${randomUUID()}.old`;
    try { await mkdir(stage); for (const [relative, content] of Object.entries(input.files)) { const file = path.join(stage, relative); await mkdir(path.dirname(file), { recursive: true }); await atomic(file, content); }
      await chmod(stage, (await stat(target)).mode & 0o777); await rename(target, old); await rename(stage, target); await rm(old, { recursive: true, force: true });
    } catch (error) { await rm(stage, { recursive: true, force: true }); try { await lstat(old); await rm(target, { recursive: true, force: true }); await rename(old, target); } catch { /* source was not swapped */ } if (error instanceof SharedSkillPoolError) throw error; throw new SharedSkillPoolError("Unable to update profile-local skill."); }
    return getProfileLocalSkill(profile, skill, options);
  });
}
